from .metrics import compute_similarity_matrix, evaluate_tvpr, print_evaluation_results
from .paths import (
    PROJECT_ROOT,
    SRC_DIR,
    DATA_DIR,
    CAPTIONS_DIR,
    VIDEOS_DIR,
    CONFIGS_DIR,
    DEFAULT_CONFIG_PATH,
    CHECKPOINTS_DIR,
    BEST_CKPT_PATH,
    LATEST_CKPT_PATH,
    OUTPUTS_DIR,
    REPORTS_DIR,
    resolve_data_root,
    resolve_config_path,
    resolve_checkpoint_path,
    resolve_output_path,
    ensure_project_dirs,
)

__all__ = [
    "compute_similarity_matrix",
    "evaluate_tvpr",
    "print_evaluation_results",
    "PROJECT_ROOT",
    "SRC_DIR",
    "DATA_DIR",
    "CAPTIONS_DIR",
    "VIDEOS_DIR",
    "CONFIGS_DIR",
    "DEFAULT_CONFIG_PATH",
    "CHECKPOINTS_DIR",
    "BEST_CKPT_PATH",
    "LATEST_CKPT_PATH",
    "OUTPUTS_DIR",
    "REPORTS_DIR",
    "resolve_data_root",
    "resolve_config_path",
    "resolve_checkpoint_path",
    "resolve_output_path",
    "ensure_project_dirs",
]
